export const BLOGS_FETCH_DATA_REQUEST = "BLOGS_FETCH_DATA_REQUEST";
export const BLOGS_FETCH_DATA_SUCCESS = "BLOGS_FETCH_DATA_SUCCESS";
export const BLOGS_FETCH_DATA_FAILURE = "BLOGS_FETCH_DATA_FAILURE";
export const BLOGS_FETCH_DATA_SINGLE_BLOG_SUCCESS =
  "BLOGS_FETCH_DATA_SINGLE_BLOG_SUCCESS";
// Single Blog
export const BLOGS_FETCH_DATA_SINGLE_BLOG_FAILURE =
  "BLOGS_FETCH_DATA_SINGLE_BLOG_FAILURE";
export const BLOGS_FETCH_DATA_SINGLE_BLOG_DELETE =
  "BLOGS_FETCH_DATA_SINGLE_BLOG_DELETE";
